### ISSUE TITLE
The bot should leave a different reaction for each topic

### ISSUE THREAD

**Issue by ruscaang** [ruscaang/type-content-bot#2]
Right now, the bot leaves only one reaction to any type of content. Because of this, it is impossible to understand what type of content the bot attributed the message to without going to a special chat. It is necessary that the type of content can be distinguished. To do this, you can use different reactions for each type of content that the bot defines. It would be possible to create a special dictionary in order to easily replenish it if content categories are added.

**Comment by Ouozen** [comment]
Alternatively, the bot should send premium emojis, in which case you need to prepare a pack and use it. But first I would check the bot's ability to send premium emojis. You can use the articles below

https://qna.habr.com/q/1212388

This method is not for aiogram, but it is fashionable to use the approach itself.

**Comment by Dimildizio** [comment]
Surprisingly there appears to be many difficulties with the emoji - from the way they are stored (currently in yaml) and encoded to their proper implementation through aiogram which rejects plenty of them. Currently the set looks as follows:

vacancies: 🦄
articles:  ✍️
courses: 🤩
files: 👍
memes: 🤡
correction: 👌

advanced ones like:
  article: 📝
  course: 📚
  correction: ✏️

somehow didn't work - either due to the encoding issue or invalid reaction from telegram itself. 
It also seems that yaml loses some data and it's not a good idea to save emojis in it. Converted to json and used utf-16 format to save them like :
{
"memes":  "\uD83E\uDD21",
"correction":  "\uD83D\uDC4C" }
